name = "FileFormatHelper"
uuid = "4d2d9364-ca76-473b-964a-083ad86fcbf9"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]
version = "0.1"

[deps]

[compat]
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test"]
